/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.loja.venda.view;

import br.edu.ifms.loja.cliente.bo.ClienteBO;
import br.edu.ifms.loja.cliente.datamodel.Cliente;
import br.edu.ifms.loja.frenteDeCaixa.view.FrenteDeCaixaFormulario;
import br.edu.ifms.loja.itemVenda.bo.ItemVendaBO;
import br.edu.ifms.loja.itemVenda.datamodel.ItemVenda;
import br.edu.ifms.loja.produto.datamodel.Produto;
import br.edu.ifms.loja.usuario.bo.UsuarioBO;
import br.edu.ifms.loja.usuario.datamodel.Usuario;
import br.edu.ifms.loja.venda.bo.VendaBO;
import br.edu.ifms.loja.venda.datamodel.Venda;
import com.towel.combo.swing.ObjectComboBoxModel;
import java.awt.Color;
import java.text.DecimalFormat;
import java.util.List;
import javax.swing.JTextField;
import java.util.Date;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author NVIDIA
 */
public class VendaFormulario extends javax.swing.JFrame {

    /**
     * Creates new form VendaFormulario
     */
    Date data = new Date();
    SimpleDateFormat formatador = new SimpleDateFormat("dd/MM/yyyy");
    private ObjectComboBoxModel<Cliente> clienteModel;
    private ObjectComboBoxModel<Usuario> usuarioModel;

    private ClienteBO clienteBO;
    private UsuarioBO usuarioBO;
    private VendaBO vendaBO;
    private ItemVendaBO itemvendaBO;
    private List<Produto> itensList;

    private Venda venda;
    private Produto produto;
    private ItemVenda itemVenda;

    double vTotal;
    DecimalFormat formato = new DecimalFormat("0.##");
    

    public VendaFormulario(Double valorTotal, List<Produto> produtos) {

        itensList = produtos;
        initComponents();
        setBackground(Color.yellow);
        campoValorTotal.setEditable(false);
        this.btFinalizarVenda.setEnabled(false);
        usuarioModel = new ObjectComboBoxModel<Usuario>();
        clienteModel = new ObjectComboBoxModel<Cliente>();
        clienteBO = new ClienteBO();
        usuarioBO = new UsuarioBO();
        vendaBO = new VendaBO();
        itemvendaBO = new ItemVendaBO();

        venda = new Venda();
        
        String dx = formato.format(valorTotal);
        vTotal = Double.parseDouble(dx.replaceAll(",", "."));
        comboBoxCliente.setModel(clienteModel);
        comboBoxVendedor.setModel(usuarioModel);
        carregarCliente();
        carregarUsuarios();
        campoValorTotal.setText(formato.format(valorTotal));
    }

    private void carregarCliente() {
        List<Cliente> clientes = clienteBO.listarTodos();
        clienteModel.setData(clientes);
        comboBoxCliente.updateUI();

    }

    private void carregarUsuarios() {
        List<Usuario> users = usuarioBO.listarTodos();
        usuarioModel.setData(users);
        comboBoxVendedor.updateUI();
    }

    public Cliente getSelectedCliente() {
        return clienteModel.getSelectedObject();
    }

    public Usuario getSelectedUsuario() {
        return usuarioModel.getSelectedObject();
    }

    public void calcularTroco() {
        double dinheiro = Double.parseDouble(getCampoDinheiro());
        double cheque = Double.parseDouble(getCampoCheque());
        double cartao = Double.parseDouble(getCampoCartao());
        double vRefeicao = Double.parseDouble(getCampoVRefeicao());
        double outros = Double.parseDouble(getCampoOutros());
        double pago = dinheiro + cheque + cartao + vRefeicao + outros;
        double troco = pago - vTotal;
        if (troco >= 0) {
            lbTroco.setForeground(Color.GREEN);
            this.lbTroco.setText("Troco: R$" + formato.format(troco));
            this.btFinalizarVenda.setEnabled(true);

        } else {
            this.btFinalizarVenda.setEnabled(false);
            lbTroco.setForeground(Color.red);
            this.lbTroco.setText("Falta: R$" + (formato.format(troco).replaceAll("-", "")));
        }

    }

    public void FinalizarVenda() {

        venda.setCliente(getSelectedCliente());
        venda.setUsuario(getSelectedUsuario());
        venda.setDataVenda(data);
        vendaBO.inserir(venda);
        
        
        itemvendaBO.inserirItens(venda, itensList, vTotal);
        JOptionPane.showMessageDialog(null, "Venda Finalizada");
        this.dispose();
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        comboBoxVendedor = new javax.swing.JComboBox<>();
        comboBoxCliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        campoValorTotal = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btFinalizarVenda = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        campoDinheiro = new javax.swing.JTextField();
        campoCartao = new javax.swing.JTextField();
        campoVRefeicao = new javax.swing.JTextField();
        campoCheque = new javax.swing.JTextField();
        campoOutros = new javax.swing.JTextField();
        panelTroco = new javax.swing.JPanel();
        lbTroco = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Venda");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        comboBoxVendedor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        comboBoxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel2.setText("Vendedor");

        jLabel3.setText("Cliente");

        jPanel1.setBackground(java.awt.SystemColor.activeCaption);
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        campoValorTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        campoValorTotal.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        campoValorTotal.setText("0.0");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("VALOR TOTAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(campoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(campoValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        btFinalizarVenda.setText("Finalizar Venda");
        btFinalizarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFinalizarVendaActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Dinheiro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Cartão");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Vale Refeicao");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Cheque");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Outros");

        campoDinheiro.setText("0.00");
        campoDinheiro.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoDinheiroFocusLost(evt);
            }
        });

        campoCartao.setText("0.00");
        campoCartao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoCartaoFocusLost(evt);
            }
        });

        campoVRefeicao.setText("0.00");
        campoVRefeicao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoVRefeicaoFocusLost(evt);
            }
        });

        campoCheque.setText("0.00");
        campoCheque.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoChequeFocusLost(evt);
            }
        });
        campoCheque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoChequeActionPerformed(evt);
            }
        });

        campoOutros.setText("0.00");
        campoOutros.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                campoOutrosFocusLost(evt);
            }
        });

        panelTroco.setBackground(java.awt.SystemColor.controlHighlight);
        panelTroco.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbTroco.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lbTroco.setForeground(java.awt.Color.green);
        lbTroco.setText("0,00");
        lbTroco.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 255, 153), 2, true));

        javax.swing.GroupLayout panelTrocoLayout = new javax.swing.GroupLayout(panelTroco);
        panelTroco.setLayout(panelTrocoLayout);
        panelTrocoLayout.setHorizontalGroup(
            panelTrocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrocoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelTrocoLayout.setVerticalGroup(
            panelTrocoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTrocoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(comboBoxVendedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(comboBoxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(73, 73, 73)
                        .addComponent(campoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(91, 91, 91)
                        .addComponent(campoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28)
                        .addComponent(campoVRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(82, 82, 82)
                        .addComponent(campoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(90, 90, 90)
                        .addComponent(campoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelTroco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btFinalizarVenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(comboBoxVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(comboBoxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(campoDinheiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campoCartao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campoVRefeicao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campoCheque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(campoOutros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFinalizarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btFinalizarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFinalizarVendaActionPerformed
        FinalizarVenda();
    }//GEN-LAST:event_btFinalizarVendaActionPerformed

    private void campoDinheiroFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoDinheiroFocusLost

        if (campoDinheiro.getText().length() > 0) {

            calcularTroco();
        } else {
            campoDinheiro.setText("0.00");
        }
    }//GEN-LAST:event_campoDinheiroFocusLost

    private void campoCartaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoCartaoFocusLost

        if (campoCartao.getText().length() > 0) {
            calcularTroco();
        } else {
            campoCartao.setText("0.00");
        }
    }//GEN-LAST:event_campoCartaoFocusLost

    private void campoVRefeicaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoVRefeicaoFocusLost

        if (campoVRefeicao.getText().length() > 0) {
            calcularTroco();
        } else {
            campoVRefeicao.setText("0.00");
        }
    }//GEN-LAST:event_campoVRefeicaoFocusLost

    private void campoChequeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoChequeFocusLost

        if (campoCheque.getText().length() > 0) {
            calcularTroco();
        } else {
            campoCheque.setText("0.00");
        }
    }//GEN-LAST:event_campoChequeFocusLost

    private void campoOutrosFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_campoOutrosFocusLost

        if (campoOutros.getText().length() > 0) {

            calcularTroco();
        } else {
            campoOutros.setText("0.00");
        }

    }//GEN-LAST:event_campoOutrosFocusLost

    private void campoChequeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoChequeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoChequeActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFinalizarVenda;
    private javax.swing.JTextField campoCartao;
    private javax.swing.JTextField campoCheque;
    private javax.swing.JTextField campoDinheiro;
    private javax.swing.JTextField campoOutros;
    private javax.swing.JTextField campoVRefeicao;
    private javax.swing.JTextField campoValorTotal;
    private javax.swing.JComboBox<String> comboBoxCliente;
    private javax.swing.JComboBox<String> comboBoxVendedor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbTroco;
    private javax.swing.JPanel panelTroco;
    // End of variables declaration//GEN-END:variables
        public String getCampoCartao() {
        return campoCartao.getText();
    }

    public void setCampoCartao(String campoCartao) {
        this.campoCartao.setText(campoCartao);
    }

    public String getCampoCheque() {
        return campoCheque.getText();///
    }

    public void setCampoCheque(String campoCheque) {
        this.campoCheque.setText(campoCheque);
    }

    public String getCampoDinheiro() {
        return campoDinheiro.getText();
    }

    public void setCampoDinheiro(String campoDinheiro) {
        this.campoDinheiro.setText(campoDinheiro);
    }

    public String getCampoOutros() {
        return campoOutros.getText();
    }

    public void setCampoOutros(String campoOutros) {
        this.campoOutros.setText(campoOutros);
    }

    public String getCampoVRefeicao() {
        return campoVRefeicao.getText();
    }

    public void setCampoVRefeicao(String campoVRefeicao) {
        this.campoVRefeicao.setText(campoVRefeicao);
    }

    public JTextField getCampoValorTotal() {
        return campoValorTotal;
    }

    public void setCampoValorTotal(JTextField campoValorTotal) {
        this.campoValorTotal = campoValorTotal;
    }

}
