/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifms.loja.app.components;

import br.edu.ifms.loja.frenteDeCaixa.view.FrenteDeCaixaFormulario;
import br.edu.ifms.loja.produto.bo.ProdutoBO;
import br.edu.ifms.loja.produto.datamodel.Produto;

import com.towel.el.annotation.AnnotationResolver;
import com.towel.swing.table.ObjectTableModel;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JTextField;

/**
 *
 * @author NVIDIA
 */
public class FormListarProdutos extends javax.swing.JFrame {

    private AnnotationResolver resolver;
    private Class clazz;
    private ProdutoBO produtosBO;
    private Produto produto;
    private FrenteDeCaixaFormulario frenCaixaFormulario;
    private String[] cabecalhoTabela = {"descricao", "marca", "valor"};

    private ObjectTableModel<Produto> prodModel;

    /**
     * Creates new form FormListarProdutos
     */
    public FormListarProdutos(FrenteDeCaixaFormulario frenCaixaForm) {
        initComponents();
        btSelecionarProduto.setEnabled(false);
        produto = new Produto();
        produtosBO = new ProdutoBO();
        frenCaixaFormulario = frenCaixaForm;

        inicializarObjectTableModel(cabecalhoTabela);

        carregarProdutos();
    }
  

    private void inicializarObjectTableModel(String[] cabecalhoTabela) {
        StringBuilder campos = new StringBuilder();
        for (String campo : cabecalhoTabela) {
            campos.append(campo);
            campos.append(",");
        }
        campos.deleteCharAt(campos.length() - 1);

        prodModel = new ObjectTableModel<Produto>(Produto.class, campos.toString());
        tabelaProduto.setModel(prodModel);
    }

    private void carregarProdutos() {
        List<Produto> listProdutos = produtosBO.listarTodos();
        prodModel.setData(listProdutos);
        tabelaProduto.updateUI();
    }

    private void aoApertarEnterNoCampoDeLocalizar() {
        List<Produto> lista = produtosBO.buscarProduto(campoLocalizar.getText());
        prodModel.setData(lista);
        tabelaProduto.updateUI();

    }

    public void aoSelecionarItemNaTabela() {
        int index = tabelaProduto.getSelectedRow();
        Produto obj = prodModel.getValue(index);
        btSelecionarProduto.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        campoLocalizar = new javax.swing.JTextField();
        btSelecionarProduto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Listar Produtos");
        setBackground(java.awt.SystemColor.activeCaption);
        setBounds(new java.awt.Rectangle(2, 2, 2, 2));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(400, 450));

        tabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Marca", "Valor"
            }
        ));
        tabelaProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaProdutoMouseClicked(evt);
            }
        });
        tabelaProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tabelaProdutoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaProdutoKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaProduto);

        jLabel1.setText("Localizar");

        campoLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoLocalizarActionPerformed(evt);
            }
        });
        campoLocalizar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                campoLocalizarKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                campoLocalizarKeyReleased(evt);
            }
        });

        btSelecionarProduto.setText("Selecionar Produto");
        btSelecionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelecionarProdutoActionPerformed(evt);
            }
        });
        btSelecionarProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                btSelecionarProdutoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(campoLocalizar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btSelecionarProduto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1))
                    .addComponent(campoLocalizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btSelecionarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoLocalizarActionPerformed

    }//GEN-LAST:event_campoLocalizarActionPerformed

    private void campoLocalizarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoLocalizarKeyPressed

    }//GEN-LAST:event_campoLocalizarKeyPressed

    private void campoLocalizarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_campoLocalizarKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            aoApertarEnterNoCampoDeLocalizar();
        }

    }//GEN-LAST:event_campoLocalizarKeyReleased

    private void btSelecionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelecionarProdutoActionPerformed
        int index = tabelaProduto.getSelectedRow();
        Produto obj = prodModel.getValue(index);
        frenCaixaFormulario.obterItemSelecionado(obj);
        this.dispose();
    }//GEN-LAST:event_btSelecionarProdutoActionPerformed

    private void tabelaProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutoKeyPressed
        aoSelecionarItemNaTabela();
    }//GEN-LAST:event_tabelaProdutoKeyPressed

    private void tabelaProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaProdutoKeyReleased
        aoSelecionarItemNaTabela();
    }//GEN-LAST:event_tabelaProdutoKeyReleased

    private void tabelaProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaProdutoMouseClicked
        aoSelecionarItemNaTabela();
    }//GEN-LAST:event_tabelaProdutoMouseClicked

    private void btSelecionarProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btSelecionarProdutoKeyReleased


    }//GEN-LAST:event_btSelecionarProdutoKeyReleased

    /**
     * @param args the command line arguments
     */
    public JTextField getCampoLocalizar() {
        return campoLocalizar;
    }

    public void setCampoLocalizar(JTextField campoLocalizar) {
        this.campoLocalizar = campoLocalizar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSelecionarProduto;
    private javax.swing.JTextField campoLocalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaProduto;
    // End of variables declaration//GEN-END:variables

}
